check50: 
  files: &check50_files
    - !exclude "*"
    - !include fizzbuzz_function.py
    - !include fizzbuzz_function_driver.py
    - !include fizzbuzz_function_solution.pyc

submit50:
  files: *check50_files
